modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    removeSentenceLineBreaks: 1
    # sentencesBeginWith:
    #   other: \$|[0-9]

fineTuning:
  modifyLineBreaks:
    betterFullStop: |-
      (?x)                                # ignore spaces in the below
      (?:                                 #
        \.\)                              # .) 
        (?!\h*[a-z])                      # not *followed by* a-z
      )                                   #
      |                                   # OR
      (?:                                 #
        (?<!                              # not *preceded by*
          (?:                             #
            (?:[eE]\.[gG])                # e.g OR E.g OR e.G OR E.G
            |                             #
            (?:[iI]\.[eE])                # i.e OR I.e OR i.E OR I.E
            |                             #
            (?:etc)                       # etc
            |                             #
            (?:[wW]\.[rR]\.[tT])          # w.r.t OR W.r.t OR w.R.t OR w.r.T OR W.R.t OR W.r.T OR w.R.T OR W.R.T
          )                               #
        )                                 #
      )                                   # 
      \.                                  # .
      (?!                                 # not *followed by*
        (?:                               #
          \),                             # ),
          |                               #
          \)\.                            # ).
          |                               #
          \}                              # }
          |                               #
          \'                              # '
          |                               #
          [a-zA-Z0-9-~,]                  # single alphanumeric exactly one time
          |                               #
          [a-zA-Z0-9-~, ]+\}              # alphanumeric including space with command end (})
          |                               #
          [a-zA-Z0-9-~, ]+\\              # alphanumeric including space with new command start (\)
        )                                 #
      )                                   #
